### ISSUE TITLE
Invalid Link for Hackerrank SDE Intern

### ISSUE THREAD

**Issue by uday03meh** [AnuvabSen1/Research_Internships_Database#1]
Hi, It seems like there is some error with the 18. Hackerrank SDE Intern link posted , it shows this on opening:
![image](https://user-images.githubusercontent.com/59679281/230632271-77581b55-4daa-4572-a7b6-c6bf87f144e6.png)

**Comment by AnuvabSen1** [comment]
Hi, I will update the md file. Thanks for the observation. Keep on suggesting more changes.
